ProfileCard, ProfilePage
DanielGamma/gts_bank_app pull request #23
Opened 2023-03-06 11:23 UTC by ceciliasegura

Hola Dani, he terminado los componentes profileCard y ProfilePage. Los he metido los dos en la rama profile_card.
Miré lo del contexto que me dijiste, pero no sabía hacerlo bien, así que les pregunte a Martin y a Millard y me dijeron que lo hiciera con getUser porque el contexto no tiene dentro el getUser y por tanto había que llamarlo así.

2023-03-06 11:29 UTC, DanielGamma requested changes

2023-03-06 11:29 UTC, DanielGamma commented on src/components/ProfileCard/ProfileCard.tsx
> +    console.log(user)
En el ticket de Trello se especifica que se debe pasar a la ProfileCard por props el nombre, mail e imagen del usuario, no se debe traer de la base de datos, y no en este componente, sino en el padre

2023-03-06 11:29 UTC, DanielGamma commented on src/components/ProfilePage/ProfilePage.tsx
> +            <NavMenu />
Es aquí donde le pasas la info por props a ProfileCard. Por otro lado, la información está en el contexto, no hace falta pedirla a la base de datos.

2023-03-06 11:29 UTC, DanielGamma commented on src/components/ProfileCard/ProfileCard.tsx
> +            <p className="font-medium text-lg text-grey-profile pt-2 ">{user.email}</p>
Aquí iría la info recibida por props

2023-03-06 19:45 UTC, ceciliasegura commented
he arreglado lo que me pediste.

2023-03-07 09:09 UTC, DanielGamma approved these changes

2023-03-07 09:09 UTC, merged